services:
  db:
    image: mysql:latest
    container_name: mysql_cine_dore
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Contraseña root
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"  # Exponer el puerto de MySQL para acceso desde la red local
    volumes:
      - db_data:/var/lib/mysql  # Volumen para persistencia de datos
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_cine_dore
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Contraseña root para conectar phpMyAdmin
    ports:
      - "8081:80"  # phpMyAdmin estará accesible en el puerto 8080
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db_data:

